### ISSUE TITLE
As a Web component Store manager I want to have the Gastronomies Web Component online

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-gastronomies#2]
- [x] @Piiit Integrate webcomp into the store
- [x] @Piiit CI pipeline missing

I know this is just the first MVP, so I think we are on a good way, just wanna quickly enumerate some issues :-)

First feedback/questions:
- [x] @lcfd No tiles shown, is there something to set in .env while building/developing/watching? Webcomp has a gray overlay... How to use it with docker-compose up?
- [x] @lcfd README incomplete: switch to yarn for instance, describe all .env vars, .env.example missing
- [x] @lcfd Widht/height not properly working, overlaps and distortion... are they accessible via CSS?
- [x] @lcfd the searchbox seems not working.
- [x] @sseppi wcs-manifest.json still misses some metadata

**Comment by Piiit** [comment]
@sseppi Please test at https://webcomponents.opendatahub.testingmachine.eu/webcomponent/f113a6c6-445f-4633-a901-b8004353c903

@lcfd See comments above

**Comment by sseppi** [comment]
@Piiit  and @lcfd from a usability point of view, do you think it could make sense to add in the configuration the number of result per page to be shown in the list view?

**Comment by Piiit** [comment]
@sseppi Yes, I think that makes sense. We should add this functionality.

**Comment by lcfd** [comment]
Hi! 
Those answers should be valid for the other issues also.

- No tiles shown, is there something to set in .env while building/developing/watching? Webcomp has a gray overlay... How to use it with docker-compose up?

The tiles don't appear because of the missing .env, I will add the parameters in the README.

I haven't used docker-compose or docker in general for those projects. I've preferred to use node directly because the docker configuration and output is directly dependent on what you are doing on your build process. Maybe you can integrate what is actually used on your server.

- README incomplete: switch to yarn for instance, describe all .env vars, .env.example missing

As written above I will add those details in the README. Anyway there's no switch to yarn, we have used yarn in other web components. No big deal, the dependencies are the same and the project should be executable also with npm.

- Widht/height not properly working, overlaps and distortion... are they accessible via CSS?

The properties of width and height are missing from a class, it should be easily fixable. There's a more compelling question, we should decide how the component works with restricted dimensions and what are the limits. We should discuss with design and Luca D'Incà how to procede on that.

- the searchbox seems not working.

The problem is the missing .env file or configurations inside it

- from a usability point of view, do you think it could make sense to add in the configuration the number of result per page to be shown in the list view?

We should discuss with design and Luca D'Incà how to procede on that. We should move to email the discussions where Luca D. is  involved.

**Comment by Piiit** [comment]
@lcfd @sseppi @GnuRant

> Hi!

Hi, and happy new year +12 ;-)

> Those answers should be valid for the other issues also.

OK.
 
>     * No tiles shown, is there something to set in .env while building/developing/watching? Webcomp has a gray overlay... How to use it with docker-compose up?
> 
> 
> The tiles don't appear because of the missing .env, I will add the parameters in the README.

I have done all the docker and .env development inside the branch "infra", which was also deployed to the store. However, I used "HERE_API_KEY" (which you used in an older web component) and not "TILES_API_KEY"... I will fix that now... 
 
> I haven't used docker-compose or docker in general for those projects. I've preferred to use node directly because the docker configuration and output is directly dependent on what you are doing on your build process. Maybe you can integrate what is actually used on your server.

It would be nice, if we could all have the same version of node and dependencies. Since, we have a large number of projects and therefore so many different versions of tools, libs, etc. ... a docker development would be nice, if applicable. I will create one with your new README and hope you like it. You can still do your development as you wish, just let me know, when you change versions or tools, such that, I can update the docker environment for us and other developers. The whole project should ideally support both equally important styles of development due to its open source character...

>     * README incomplete: switch to yarn for instance, describe all .env vars, .env.example missing
> 
> 
> As written above I will add those details in the README. Anyway there's no switch to yarn, we have used yarn in other web components. No big deal, the dependencies are the same and the project should be executable also with npm.

With "switch to yarn" I meant the to-dos inside the README... npm or yarn, both are OK for us.

>     * Widht/height not properly working, overlaps and distortion... are they accessible via CSS?
> 
> The properties of width and height are missing from a class, it should be easily fixable. There's a more compelling question, we should decide how the component works with restricted dimensions and what are the limits. We should discuss with design and Luca D'Incà how to procede on that.

OK. I will discuss that with @sseppi and let you know.

>     * the searchbox seems not working.
> 
> The problem is the missing .env file or configurations inside it

Fixed for "gastronomies", I will have a look at other components asap...

>     * from a usability point of view, do you think it could make sense to add in the configuration the number of result per page to be shown in the list view?
> 
> 
> We should discuss with design and Luca D'Incà how to procede on that. We should move to email the discussions where Luca D. is involved.

OK, let us continue there for design questions, but I would like to still keep issues and our Kanban for task tracking...
Hope that is fine for you all...

**Comment by lcfd** [comment]
> Since, we have a large number of projects and therefore so many different versions of tools, libs, etc. ... a docker development would be nice, if applicable.

Of course, no problems I haven't done that for practical reasons. Now that we have a docker env with your preferences and needs you can merge your branch and I will use it.

> With "switch to yarn" I meant the to-dos inside the README... npm or yarn, both are OK for us.

Ok, perfect, there was a misunderstanding.

> OK. I will discuss that with @sseppi and let you know.

I'm trying to make it work. With the next PR (to the meteo widget) you'll see it.

> OK, let us continue there for design questions, but I would like to still keep issues and our Kanban for task tracking...
Hope that is fine for you all...

No problems, I'll answer here as well for technical matters but if it's a more than 1to1 between me and you I think it would be better use emails. For the kanban no problem as well, we use other internal tools also.

**Comment by lcfd** [comment]
@sseppi @Piiit

This should be solved

cc @GnuRant
